### ISSUE TITLE
اینا کجا هستند ؟

### ISSUE THREAD

**Issue by Manimrx110022** [NeverWonderLand/nbp-persian#1]
![IMG_20221016_220328.jpg](https://user-images.githubusercontent.com/113861666/196052045-45d8f933-c74c-4636-a7bb-a0a58930473a.jpg)

**Comment by ghostwond3r** [comment]
https://github.com/NeverWonderLand/nbp-persian/blob/main/kali_install.md

https://github.com/NeverWonderLand/nbp-persian/blob/main/terminal.md

https://github.com/NeverWonderLand/nbp-persian/blob/main/REF_terminal.md
